#!/usr/bin/env bash

set -e

poetry run isort --check scratchgpt
poetry run black --check scratchgpt
poetry run mypy --strict scratchgpt
poetry run bandit --recursive --skip B105,B614,B403,B301 scratchgpt
poetry run pytest tests/
